#https://hub.docker.com/r/bioconductor/bioconductor_docker/tags?page=1&ordering=last_updated
FROM bioconductor/bioconductor_docker:RELEASE_3_13

MAINTAINER Shaojun Xie

# This will make apt-get install without question
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y apt-utils \
    	    	       libudunits2-dev \
		       libhdf5-dev \
		       gdal-bin \
		       proj-bin \
		       libproj-dev \
		       libgsl-dev \
		       libxml2 \
		       libxml2-dev \
		       libigraph0-dev \
		       zlib1g-dev \
		       libtool \
		       bison \
		       flex \
		       automake \
		       autoconf \
		       libpng*-dev \
		       libglpk-dev \
		       xorg \
		       libx11-dev \
		       libglu1-mesa-dev \
		       libfreetype*-dev \
		       p7zip \
		       build-essential \
		       libssl-dev \
		       libffi-dev \
		       libxslt1-dev \
		       python3 \
		       python-dev \
		       python3-dev \
		       python3-pip \
		       libxt-dev \
		       libgtk2.0-dev \
		       libcairo2-dev \
		       xvfb \
		       xauth \
		       xfonts-base

# update pip
# update pip
RUN pip install --upgrade pip
RUN pip3 install --upgrade pip
# install wheel
RUN pip install wheel
RUN pip install jupyterlab==2.2.8
## https://github.com/jupyterlab/jupyterlab-toc
## x means 12 here
RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash -
RUN apt-get install -y nodejs
RUN jupyter labextension install @jupyterlab/toc


RUN R -e 'install.packages("devtools")'
RUN R -e 'install.packages("pkgbuild")'

# install cran packages
#ADD install_cran.R /tmp/
#RUN R -f /tmp/install_cran.R

#clusterProfiler
RUN R -e 'devtools::install_version("clusterProfiler", version="4.0.2", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)'


RUN R -e 'devtools::install_version("IRkernel", version = "1.1.1", repos = "https://cran.rstudio.com/",upgrade = "never", force = TRUE)'
RUN R -e 'IRkernel::installspec(name = "R", displayname = "R-4.0.2", user = FALSE)'
## 1.18.1
RUN R -e 'devtools::install_version("ggnewscale", version="0.4.5", repos=c("http://cran.us.r-project.org"),upgrade = "never", force = TRUE)'
RUN R -e 'devtools::install_version("org.Hs.eg.db", version="3.13.0", repos="https://bioconductor.org/packages/3.13/data/annotation",upgrade = "never", force = TRUE)'
RUN R -e 'devtools::install_version("org.Dm.eg.db", version="3.13.0", repos=c("https://bioconductor.org/packages/3.13/data/annotation"),upgrade = "never", force = TRUE)'

RUN R -e 'devtools::install_version("XML", version="3.99-0.6", repos=c("http://cran.us.r-project.org"),upgrade = "never", force = TRUE)'
#1.34.0
RUN R -e 'devtools::install_version("AnnotationForge", version="1.34.0", repos=c("https://bioconductor.org/packages/3.13/data/annotation", "https://bioconductor.org/packages/3.13/bioc"),upgrade = "never", force = TRUE)'
RUN R -e 'devtools::install_github("guokai8/bioAnno", version="0.99.35")'
RUN pip3 install snakemake==6.6.1
RUN curl -L http://cpanmin.us | perl - --sudo Excel::Writer::XLSX

#RUN pip install XlsxWriter==1.3.3
#RUN apt-get remove --purge -y $BUILDPKGS && \
#    rm -rf /var/lib/apt/lists/*
USER docker
WORKDIR /home/docker/
#ENTRYPOINT ["/usr/bin/docker_helper.0.1.0"]

