

```
docker build -t scrna.doublecollection.1.1.0 -f Dockerfile.scRNAseqDoubleCollection.1.1.0 .
docker tag scrna.doublecollection.1.1.0 xie186/r4bix:doublecollection.1.1.0
docker push xie186/r4bix:doublecollection.1.1.0 
```
