#https://hub.docker.com/r/bioconductor/bioconductor_docker/tags?page=1&ordering=last_updated
FROM bioconductor/bioconductor_docker:RELEASE_3_13

MAINTAINER Shaojun Xie

# This will make apt-get install without question
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y apt-utils \
    	    	       libudunits2-dev \
		       libhdf5-dev \
		       gdal-bin \
		       proj-bin \
		       libproj-dev \
		       libgsl-dev \
		       libxml2 \
		       libxml2-dev \
		       libigraph0-dev \
		       zlib1g-dev \
		       libtool \
		       bison \
		       flex \
		       automake \
		       autoconf \
		       libpng*-dev \
		       libglpk-dev \
		       xorg \
		       libx11-dev \
		       libglu1-mesa-dev \
		       libfreetype*-dev \
		       p7zip \
		       build-essential \
		       libssl-dev \
		       libffi-dev \
		       libxslt1-dev \
		       python3 \
		       python-dev \
		       python3-dev \
		       python3-pip \
		       libxt-dev \
		       libgtk2.0-dev \
		       libcairo2-dev \
		       xvfb \
		       xauth \
		       xfonts-base

# update pip
# update pip
RUN pip install --upgrade pip
RUN pip3 install --upgrade pip
# install wheel
RUN pip install wheel
RUN pip install jupyterlab==2.2.8
## https://github.com/jupyterlab/jupyterlab-toc
## x means 12 here
RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash -
RUN apt-get install -y nodejs
RUN jupyter labextension install @jupyterlab/toc


RUN R -e 'install.packages("devtools")'
RUN R -e 'install.packages("pkgbuild")'

# install cran packages
#ADD install_cran.R /tmp/
#RUN R -f /tmp/install_cran.R

#clusterProfiler
#RUN R -e 'devtools::install_version("clusterProfiler", version="4.0.2", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)'


RUN R -e 'devtools::install_version("IRkernel", version = "1.1.1", repos = "https://cran.rstudio.com/",upgrade = "never", force = TRUE)'
RUN R -e 'IRkernel::installspec(name = "R", displayname = "R-4.0.2", user = FALSE)'
RUN pip3 install snakemake==6.6.1

# mutoss
RUN R -e 'devtools::install_version("mutoss", version = "0.1-12", repos = "https://cran.rstudio.com/",upgrade = "never", force = TRUE)'

RUN R -e 'devtools::install_version("clustree", version = "0.4.3", repos = "https://cran.rstudio.com/",upgrade = "never", force = TRUE)'


RUN R -e 'install.packages("remotes")'
# R.utils
RUN R -e 'devtools::install_version("R.utils", version = "2.10.1", repos = "https://cran.rstudio.com/",upgrade = "never", force = TRUE)'
#RUN R -e 'remotes::install_github("satijalab/seurat-wrappers")'
RUN R -e 'devtools::install_version("ggthemes", version = "4.2.4", repos = "https://cran.rstudio.com/",upgrade = "never", force = TRUE)'
RUN R -e 'devtools::install_version("Seurat", version = "3.1.1", repos = "https://cran.rstudio.com/",upgrade = "never", force = TRUE)'

RUN R -e 'devtools::install_version("ztable", version = "0.2.2", repos = "https://cran.rstudio.com/",upgrade = "never", force = TRUE)'

#RUN R -e 'ip = as.data.frame(installed.packages()[,c(1,3:4)]); ip = ip[is.na(ip$Priority),1:2,drop=FALSE];    ip'

RUN useradd -s /bin/bash docker
USER docker
WORKDIR /home/docker/
#ENTRYPOINT ["/usr/bin/docker_helper.0.1.0"]

