#https://hub.docker.com/r/bioconductor/bioconductor_docker/tags?page=1&ordering=last_updated
FROM bioconductor/bioconductor_docker:RELEASE_3_15

MAINTAINER Shaojun Xie

# This will make apt-get install without question
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y apt-utils \
    	    	       libudunits2-dev \
		       libhdf5-dev \
		       gdal-bin \
		       proj-bin \
		       libproj-dev \
		       libgsl-dev \
		       libxml2 \
		       libxml2-dev \
		       libigraph0-dev \
		       zlib1g-dev \
		       libtool \
		       bison \
		       flex \
		       automake \
		       autoconf \
		       libpng*-dev \
		       libglpk-dev \
		       xorg \
		       libx11-dev \
		       libglu1-mesa-dev \
		       libfreetype*-dev \
		       p7zip \
		       build-essential \
		       libssl-dev \
		       libffi-dev \
		       libxslt1-dev \
		       python3 \
		       python-dev \
		       python3-dev \
		       python3-pip \
		       libxt-dev \
		       libgtk2.0-dev \
		       libcairo2-dev \
		       xvfb \
		       xauth \
		       xfonts-base

# update pip
RUN pip install --upgrade pip
# install wheel
RUN pip install wheel
RUN pip install jupyterlab==3.4.5
## https://github.com/jupyterlab/jupyterlab-toc
## x means 12 here
RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash -
RUN apt-get install -y nodejs
RUN jupyter labextension install @jupyterlab/toc


RUN R -e 'install.packages("devtools")'
RUN R -e 'install.packages("pkgbuild")'

# install cran packages
#ADD install_cran.R /tmp/
#RUN R -f /tmp/install_cran.R

RUN R -e 'devtools::install_version("IRkernel", version = "1.1.1", repos = "https://cran.rstudio.com/",upgrade = "never", force = TRUE)'
RUN R -e 'IRkernel::installspec(name = "R", displayname = "R", user = FALSE)'
RUN pip install snakemake==7.12.1


## Version: Seurat (v4.1.0)
RUN R -e 'devtools::install_version("Seurat", version = "4.1.1", repos = "https://cran.rstudio.com/",upgrade = "never", force = TRUE)'
## Version: openxlsx (v4.2.5)
RUN R -e 'devtools::install_version("openxlsx", version = "4.2.5", repos = "https://cran.rstudio.com/",upgrade = "never", force = TRUE)'
## Version: tidyverse (v1.3.1)
RUN R -e 'devtools::install_version("tidyverse", version = "1.3.1", repos = "https://cran.rstudio.com/",upgrade = "never", force = TRUE)'

## Jan 31, 2022
RUN R -e 'devtools::install_github("chris-mcginnis-ucsf/DoubletFinder@67fb8b5808eb16167ead5f9b439677cc24837554")'

## Version: UpsetR (v1.4.0)
RUN R -e 'devtools::install_version("UpSetR", version = "1.4.0", repos = "https://cran.rstudio.com/",upgrade = "never", force = TRUE)'
## Version: edgeR (v3.36.0)
RUN R -e 'devtools::install_version("edgeR", version="3.38.4", repos=c("https://bioconductor.org/packages/3.15/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)'
## 

RUN R -e 'devtools::install_github("jbergenstrahle/STUtility@1.1.1")'
## Version: scProportionTest (v1.0.0)
RUN R -e 'devtools::install_github("rpolicastro/scProportionTest@v1.0.0")'

RUN R -e 'devtools::install_github("satijalab/seurat-data@d6a8ce61ccb21a3b204f194d07009772c822791d")'
RUN R -e 'devtools::install_version("hdf5r", version = "1.3.5", repos = "https://cran.rstudio.com/",upgrade = "never", force = TRUE)'

# 6866e01 on Jun 23 Git stats 160 commits
RUN R -e 'devtools::install_github("immunogenomics/harmony@6866e01e4d7e1729b46e98303ac7c38be1036248")'

## Version: edgeR (v3.36.0)
RUN R -e 'devtools::install_github("saezlab/dorothea@22d6036ed37613ff8f725b5808d6958944f51e2a")'
RUN R -e 'devtools::install_version("cowplot", version = "1.1.1", repos = "https://cran.rstudio.com/",upgrade = "never", force = TRUE)'



## Version: oct4th (v1.0.1)
RUN pip install oct4th==1.0.1
RUN pip install rpy2==3.5.3

USER root

RUN rm -rf /usr/bin/pip /usr/bin/python && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    ln -s /usr/bin/pip3 /usr/bin/pip


## List of user-installed R packages and their versions
## https://stackoverflow.com/a/40120266/3327344
RUN R -e 'ip = as.data.frame(installed.packages()[,c(1,3:4)]); ip = ip[is.na(ip$Priority),1:2,drop=FALSE];ip'

RUN useradd -s /bin/bash docker
USER docker
WORKDIR /home/docker/

#ENTRYPOINT ["/usr/bin/docker_helper.0.1.0"]

########################################################################
## docker build -t scrna.st.0.1 -f Dockerfile.scRNAseq4st.0.1 .
## docker tag scrna.st.0.1 xie186/r4bix:scrna.st.0.1
## docker push xie186/r4bix:scrna.st.0.1
   
## singularity -d build --force scrna.st.0.1.img docker://xie186/r4bix:scrna.st.0.1

## singularity run --nv scrna.st.0.1.img jupyter-lab --ip=<IP> --port=<PORT> --no-browser
##  --NotebookApp.token='bix123' --allow-root
## 
## singularity exec scrna.st.0.1.img snakemake -s 
## DEG_scRNA_treatment.py --configfile config_PDX.yaml -j 4
##

## For test
## docker run -e PASSWORD=password -e USERID=$(id -u)  -d scrna.st.0.1:latest
## The command above will generate an ID. 
## docker container ls
## docker exec -it  1884426c3827 python3
##########################################################################
