#https://hub.docker.com/r/bioconductor/bioconductor_docker/tags?page=1&ordering=last_updated
FROM bioconductor/bioconductor_docker:RELEASE_3_13

MAINTAINER Shaojun Xie

# This will make apt-get install without question
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y apt-utils \
    	    	       libudunits2-dev \
		       libhdf5-dev \
		       gdal-bin \
		       proj-bin \
		       libproj-dev \
		       libgsl-dev \
		       libxml2 \
		       libxml2-dev \
		       libigraph0-dev \
		       zlib1g-dev \
		       libtool \
		       bison \
		       flex \
		       automake \
		       autoconf \
		       libpng*-dev \
		       libglpk-dev \
		       xorg \
		       libx11-dev \
		       libglu1-mesa-dev \
		       libfreetype*-dev \
		       p7zip \
		       build-essential \
		       libssl-dev \
		       libffi-dev \
		       libxslt1-dev \
		       python3 \
		       python-dev \
		       python3-dev \
		       python3-pip \
		       libxt-dev \
		       libgtk2.0-dev \
		       libcairo2-dev \
		       xvfb \
		       xauth \
		       xfonts-base

# update pip
# update pip
RUN pip install --upgrade pip
RUN pip3 install --upgrade pip
# install wheel
RUN pip install wheel
RUN pip install jupyterlab==2.2.8
## https://github.com/jupyterlab/jupyterlab-toc
## x means 12 here
RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash -
RUN apt-get install -y nodejs
RUN jupyter labextension install @jupyterlab/toc


RUN R -e 'install.packages("devtools")'
RUN R -e 'install.packages("pkgbuild")'

# install cran packages
#ADD install_cran.R /tmp/
#RUN R -f /tmp/install_cran.R

#clusterProfiler
#RUN R -e 'devtools::install_version("clusterProfiler", version="4.0.2", repos=c("https://bioconductor.org/packages/3.13/bioc","http://cran.us.r-project.org"),upgrade = "never", force = TRUE)'


RUN R -e 'devtools::install_version("IRkernel", version = "1.1.1", repos = "https://cran.rstudio.com/",upgrade = "never", force = TRUE)'
RUN R -e 'IRkernel::installspec(name = "R", displayname = "R-4.0.2", user = FALSE)'
RUN pip3 install snakemake==6.6.1

RUN R -e 'install.packages("remotes")'
## Version: Seurat 4.0.4
RUN R -e 'devtools::install_version("Seurat", version = "4.0.4", repos = "https://cran.rstudio.com/",upgrade = "never", force = TRUE)'
## Version: dplyr 1.0.7
RUN R -e 'devtools::install_version("dplyr", version = "1.0.7", repos = "https://cran.rstudio.com/",upgrade = "never", force = TRUE)'

##  Lastest version on 10/14/2021

## Version: DoubletCollection@d7383e9cd72dbbf6a4a7b1b124d571489768fce0
RUN R -e 'devtools::install_github("xnnba1984/DoubletCollection@d7383e9cd72dbbf6a4a7b1b124d571489768fce0")'
## Version: scrublet==0.2.3
RUN pip3 install scrublet==0.2.3
## Version: doubletdetection==3.0
RUN pip3 install doubletdetection==3.0

## Version: Leidenbase 0.1.3
## 430f22af6982cc7d2e6e77f6b0df47bc970dcbce Leidenbase 0.1.3 Latest
RUN R -e 'devtools::install_github("cole-trapnell-lab/leidenbase@430f22af6982cc7d2e6e77f6b0df47bc970dcbce")'
## Version: Monocle 3 1.0.0
## 004c096f3a3bdaf1e6709a65fb36f40ba775f1ab Monocle 3 1.0.0 Latest
RUN R -e 'devtools::install_github("cole-trapnell-lab/monocle3@004c096f3a3bdaf1e6709a65fb36f40ba775f1ab")'
## Version: Garnett 0.1.13
## Latest c68439142f3069db2c6f1333a7a4c22979db7186
RUN R -e 'devtools::install_github("cole-trapnell-lab/garnett@c68439142f3069db2c6f1333a7a4c22979db7186")'


RUN useradd -s /bin/bash docker
USER docker
WORKDIR /home/docker/
#ENTRYPOINT ["/usr/bin/docker_helper.0.1.0"]


#################################
# docker build -t scrna.seurat4.0.4 -f Dockerfile.scRNAseq.seurat4.0.4 .
# docker tag scrna.seurat4.0.4 xie186/r4bix:seurat4.0.4
# docker push xie186/r4bix:seurat4.0.4
#################################
